import type { RecruitmentCandidate, RecruitmentRole } from "./model";

export const previewRecruitmentCandidates: RecruitmentCandidate[] = [
  { id: "preview-candidate-1", name: "Alex Morgan", email: "alex@example.test", roles: ["Senior Marketer"], status: "Shortlist", location: "Lisbon, Portugal", schedule: ["Regular"], notes: "Strong portfolio and relevant remote-team experience.", createdAt: "2026-07-08T09:20:00.000Z", updatedAt: "2026-07-14T08:30:00.000Z", attachments: [{ id: "resume-1", filename: "Alex-Morgan-CV.pdf", url: "https://example.test/alex-cv.pdf", type: "application/pdf" }], comments: [{ id: "comment-1", body: "The portfolio feels unusually thoughtful. I’d move Alex into the first interview this week.", authorName: "Dee Urosevic", authorInitials: "DU", createdAt: "2026-07-14T08:35:00.000Z" }, { id: "comment-2", body: "Agreed. I can take the interview on Thursday afternoon.", authorName: "Olivia Martin", authorInitials: "OM", createdAt: "2026-07-14T09:10:00.000Z" }] },
  { id: "preview-candidate-2", name: "Maya Chen", email: "maya@example.test", roles: ["Senior Marketer"], status: "Interview", location: "Taipei, Taiwan", schedule: ["Regular"], interviewer: "Dee", firstInterviewNotes: "Clear communicator with excellent channel strategy examples.", createdAt: "2026-07-09T10:05:00.000Z", updatedAt: "2026-07-14T10:12:00.000Z", attachments: [], comments: [] },
  { id: "preview-candidate-3", name: "Jon Bell", email: "jon@example.test", roles: ["Operations Assistant"], status: "Unreviewed", location: "Manchester, UK", schedule: ["Evening + Weekend"], createdAt: "2026-07-13T13:00:00.000Z", updatedAt: "2026-07-13T13:00:00.000Z", attachments: [], comments: [] },
  { id: "preview-candidate-4", name: "Priya Rao", email: "priya@example.test", roles: ["Operations Assistant"], status: "Challenge", location: "Bengaluru, India", schedule: ["Regular"], notes: "Scenario challenge due Friday.", createdAt: "2026-07-03T11:40:00.000Z", updatedAt: "2026-07-12T15:22:00.000Z", attachments: [], comments: [] },
  { id: "preview-candidate-5", name: "Leo Martins", email: "leo@example.test", roles: ["Booking Manager LATAM"], status: "2nd Interview", location: "São Paulo, Brazil", schedule: ["Regular"], interviewer: "Olivia", createdAt: "2026-06-26T08:14:00.000Z", updatedAt: "2026-07-11T09:05:00.000Z", attachments: [], comments: [] },
  { id: "preview-candidate-6", name: "Nora Ibrahim", email: "nora@example.test", roles: ["Trip Design Assistant"], status: "Final Round", location: "Amman, Jordan", schedule: ["Regular"], interviewer: "Justin", createdAt: "2026-06-28T14:42:00.000Z", updatedAt: "2026-07-14T07:45:00.000Z", attachments: [], comments: [] },
  { id: "preview-candidate-7", name: "Sam Rivera", email: "sam@example.test", roles: ["Operations Assistant"], status: "Next opening", location: "Medellín, Colombia", schedule: ["Regular"], createdAt: "2026-06-20T12:20:00.000Z", updatedAt: "2026-07-10T12:00:00.000Z", attachments: [], comments: [] },
];

export const previewRecruitmentRoles: RecruitmentRole[] = [
  { title: "Senior Marketer", status: "live", hiringManager: "Dee Urosevic", location: "Remote · Europe", employmentType: "Full-time", adCopy: "Lead growth and brand marketing across a portfolio of distinctive travel brands.", adUrl: "https://example.test/jobs/senior-marketer", advertisingChannels: ["LinkedIn", "We Work Remotely"], publishingNotes: "Refresh LinkedIn post on Monday.", updatedAt: "2026-07-14T08:00:00.000Z", activeCandidates: 2 },
  { title: "Operations Assistant", status: "ready", hiringManager: "Olivia Martin", location: "Remote · Americas", employmentType: "Full-time", adCopy: "Help our operations team deliver smooth, thoughtful trips for every traveller.", advertisingChannels: ["LinkedIn", "Remote Jobs LATAM"], publishingNotes: "Waiting for final application link.", updatedAt: "2026-07-13T16:00:00.000Z", activeCandidates: 3 },
];
