import type { AccessSnapshot, AuditEvent, VerifiedIdentity } from "./model";
import {
  APP_BUILDER_ADMIN_ROLE_ID,
  APP_BUILDER_APPLICATION_ID,
  APP_BUILDER_APPLICATION_SLUG,
  APP_BUILDER_USER_ROLE_ID,
  RECRUITMENT_ADMIN_ROLE_ID,
  RECRUITMENT_APPLICATION_ID,
  RECRUITMENT_APPLICATION_SLUG,
  RECRUITMENT_USER_ROLE_ID,
  SUPERPANEL_ADMIN_ROLE_ID,
  SUPERPANEL_APPLICATION_ID,
  SUPERPANEL_APPLICATION_SLUG,
  SUPERPANEL_USER_ROLE_ID,
} from "./application-ids.ts";

export const PREVIEW_NOW = new Date("2026-07-14T09:00:00.000Z");

const employeeIssuer = "https://identity.cove-demo.test/workspace-simulator";
const partnerIssuer = "https://identity.cove-demo.test/partner-simulator";

export const previewIdentities = {
  operations: {
    subject: "preview-google-sub-cove-admin",
    issuer: employeeIssuer,
    population: "employee",
    email: "admin@cove-demo.test",
    emailVerified: true,
    verifiedAt: "2026-07-14T08:55:00.000Z",
    workspaceDomain: "cove-demo.test",
    sessionId: "preview-session-operations",
  },
  analyst: {
    subject: "preview-google-sub-analyst",
    issuer: employeeIssuer,
    population: "employee",
    email: "analyst@cove-demo.test",
    emailVerified: true,
    verifiedAt: "2026-07-14T08:55:00.000Z",
    workspaceDomain: "cove-demo.test",
    sessionId: "preview-session-analyst",
  },
  supplier: {
    subject: "preview-partner-sub-supplier",
    issuer: partnerIssuer,
    population: "external_partner",
    email: "supplier.preview@example.test",
    emailVerified: true,
    verifiedAt: "2026-07-14T08:55:00.000Z",
    sessionId: "preview-session-supplier",
  },
} as const satisfies Record<string, VerifiedIdentity>;

export const previewAccessSnapshot: AccessSnapshot = {
  partnerOrganisations: [
    { id: "partner-sunbird", name: "Sunbird Safaris (preview)", status: "active" },
  ],
  users: [
    {
      id: "user-operations",
      identitySubject: previewIdentities.operations.subject,
      identityIssuer: employeeIssuer,
      population: "employee",
      email: previewIdentities.operations.email,
      displayName: "Cove Preview Admin",
      status: "active",
      workspaceDomain: "cove-demo.test",
      platformRoles: ["super_admin"],
      sessionVersion: 1,
    },
    {
      id: "user-analyst",
      identitySubject: previewIdentities.analyst.subject,
      identityIssuer: employeeIssuer,
      population: "employee",
      email: previewIdentities.analyst.email,
      displayName: "Jordan Analyst",
      status: "active",
      workspaceDomain: "cove-demo.test",
      platformRoles: ["auditor"],
      sessionVersion: 1,
    },
    {
      id: "user-supplier",
      identitySubject: previewIdentities.supplier.subject,
      identityIssuer: partnerIssuer,
      population: "external_partner",
      email: previewIdentities.supplier.email,
      displayName: "Sam Supplier",
      status: "active",
      partnerOrganisationId: "partner-sunbird",
      platformRoles: [],
      sessionVersion: 1,
    },
  ],
  teams: [
    {
      id: "team-operations",
      name: "Operations",
      description: "Internal trip operations team",
      status: "active",
    },
    {
      id: "team-insights",
      name: "Insights",
      description: "Restricted analytics users",
      status: "active",
    },
  ],
  teamMemberships: [
    { teamId: "team-operations", userId: "user-operations" },
    { teamId: "team-insights", userId: "user-operations" },
    { teamId: "team-insights", userId: "user-analyst" },
  ],
  applications: [
    {
      id: "app-booking",
      slug: "booking",
      name: "Booking",
      description: "Guest call scheduling for Booking Managers — availability, routing, reminders and the trip-page widget",
      launchUrl: "https://cove.leatherbacktravel.com/booking",
      owner: "Booking Operations",
      status: "active",
      risk: "restricted",
      allowedPopulations: ["employee"],
    },
    {
      id: APP_BUILDER_APPLICATION_ID,
      slug: APP_BUILDER_APPLICATION_SLUG,
      name: "App Builder",
      description: "Controlled AI-assisted updates for Cove applications",
      launchUrl: "https://cove.leatherbacktravel.com/app-builder",
      owner: "Systems & Automation",
      status: "active",
      risk: "restricted",
      allowedPopulations: ["employee"],
    },
    {
      id: RECRUITMENT_APPLICATION_ID,
      slug: RECRUITMENT_APPLICATION_SLUG,
      name: "Recruitment",
      description: "Internal candidate pipeline and role advertising workspace",
      launchUrl: "https://cove.leatherbacktravel.com/recruitment",
      owner: "People & Operations",
      status: "active",
      risk: "restricted",
      allowedPopulations: ["employee"],
    },
    {
      id: SUPERPANEL_APPLICATION_ID,
      slug: SUPERPANEL_APPLICATION_SLUG,
      name: "SuperPanel",
      description: "Systems administration for Leatherback Travel applications and websites",
      launchUrl: "https://cove.leatherbacktravel.com/systems",
      owner: "Leatherback Travel Systems",
      status: "active",
      risk: "restricted",
      allowedPopulations: ["employee"],
    },
    {
      id: "app-trtl",
      slug: "trtl",
      name: "TRTL",
      description: "Trips, bookings and operational workflow",
      launchUrl: "https://trtl.leatherbacktravel.com",
      repository: {
        path: "leatherback-travel-organisation/trtl",
        href: "https://github.com/leatherback-travel-organisation/trtl",
      },
      owner: "Operations",
      status: "active",
      risk: "restricted",
      allowedPopulations: ["employee"],
    },
    {
      id: "app-answers",
      slug: "leatherback-answers",
      name: "Leatherback Answers",
      description: "Restricted natural-language business analytics",
      launchUrl: "https://answers.leatherbacktravel.com",
      repository: {
        path: "leatherback-travel-organisation/leatherback-answers",
        href: "https://github.com/leatherback-travel-organisation/leatherback-answers",
      },
      owner: "Leadership",
      status: "active",
      risk: "restricted",
      allowedPopulations: ["employee"],
    },
    {
      id: "app-supplier-portal",
      slug: "supplier-portal",
      name: "Supplier Portal",
      description: "Shared supplier workflow for employees and invited partners",
      launchUrl: "https://suppliers.leatherbacktravel.com",
      repository: {
        path: "leatherback-travel-organisation/leatherback-supplier-portal-v2",
        href: "https://github.com/leatherback-travel-organisation/leatherback-supplier-portal-v2",
      },
      owner: "Supplier Operations",
      status: "active",
      risk: "sensitive",
      allowedPopulations: ["employee", "external_partner"],
    },
    {
      id: "app-1mwu",
      slug: "1mwu",
      name: "1MWU",
      description: "Shared 1MWU planning and operations spreadsheet",
      launchUrl: "https://docs.google.com/spreadsheets/d/1KuxRxUy5MlUNof1dC7oGuHRomsb5wDqBJC3fFPTeXN0/edit?gid=0#gid=0",
      owner: "Operations",
      status: "active",
      risk: "standard",
      allowedPopulations: ["employee"],
    },
    {
      id: "app-money",
      slug: "money",
      name: "Your Money",
      description: "Invoices, travel credits and reimbursements",
      launchUrl: "https://cove.leatherbacktravel.com/money",
      owner: "Finance",
      status: "active",
      risk: "sensitive",
      allowedPopulations: ["employee"],
    },
    {
      id: "app-injuries",
      slug: "injuries",
      name: "Injury Reporting",
      description: "Private workplace injury reporting",
      launchUrl: "https://cove.leatherbacktravel.com/injuries",
      owner: "People & Operations",
      status: "active",
      risk: "restricted",
      allowedPopulations: ["employee"],
    },
  ],
  roles: [
    {
      id: "role-booking-user",
      applicationId: "app-booking",
      key: "user",
      name: "Booking Manager",
      level: "user",
      permissions: ["booking.open", "booking.read", "booking.manage_own"],
      allowedPopulations: ["employee"],
    },
    {
      id: "role-booking-admin",
      applicationId: "app-booking",
      key: "admin",
      name: "Pod Lead",
      level: "admin",
      permissions: ["booking.open", "booking.read", "booking.manage_own", "booking.manage"],
      allowedPopulations: ["employee"],
    },
    {
      id: APP_BUILDER_USER_ROLE_ID,
      applicationId: APP_BUILDER_APPLICATION_ID,
      key: "user",
      name: "App Builder User",
      level: "user",
      permissions: ["app_builder.read", "app_builder.submit"],
      allowedPopulations: ["employee"],
    },
    {
      id: APP_BUILDER_ADMIN_ROLE_ID,
      applicationId: APP_BUILDER_APPLICATION_ID,
      key: "admin",
      name: "App Builder Admin",
      level: "admin",
      permissions: ["app_builder.read", "app_builder.submit", "app_builder.approve", "app_builder.configure", "app_builder.manage_access"],
      allowedPopulations: ["employee"],
    },
    {
      id: RECRUITMENT_USER_ROLE_ID,
      applicationId: RECRUITMENT_APPLICATION_ID,
      key: "user",
      name: "Recruitment User",
      level: "user",
      permissions: ["recruitment.read", "recruitment.manage_candidates", "recruitment.manage_roles"],
      allowedPopulations: ["employee"],
    },
    {
      id: RECRUITMENT_ADMIN_ROLE_ID,
      applicationId: RECRUITMENT_APPLICATION_ID,
      key: "admin",
      name: "Recruitment Admin",
      level: "admin",
      permissions: ["recruitment.read", "recruitment.manage_candidates", "recruitment.manage_roles", "recruitment.manage_access"],
      allowedPopulations: ["employee"],
    },
    {
      id: SUPERPANEL_USER_ROLE_ID,
      applicationId: SUPERPANEL_APPLICATION_ID,
      key: "user",
      name: "SuperPanel User",
      level: "user",
      permissions: ["superpanel.open"],
      allowedPopulations: ["employee"],
    },
    {
      id: SUPERPANEL_ADMIN_ROLE_ID,
      applicationId: SUPERPANEL_APPLICATION_ID,
      key: "admin",
      name: "SuperPanel Admin",
      level: "admin",
      permissions: ["superpanel.open", "superpanel.manage_access"],
      allowedPopulations: ["employee"],
    },
    {
      id: "role-trtl-member",
      applicationId: "app-trtl",
      key: "member",
      name: "TRTL member",
      level: "user",
      permissions: ["trtl.read", "trtl.update"],
      allowedPopulations: ["employee"],
    },
    {
      id: "role-trtl-admin",
      applicationId: "app-trtl",
      key: "admin",
      name: "TRTL admin",
      level: "admin",
      permissions: ["trtl.read", "trtl.update", "trtl.manage_access"],
      allowedPopulations: ["employee"],
    },
    {
      id: "role-answers-analyst",
      applicationId: "app-answers",
      key: "analyst",
      name: "Answers analyst",
      level: "user",
      permissions: ["answers.ask", "answers.read_results"],
      allowedPopulations: ["employee"],
    },
    {
      id: "role-answers-admin",
      applicationId: "app-answers",
      key: "admin",
      name: "Answers admin",
      level: "admin",
      permissions: ["answers.ask", "answers.read_results", "answers.manage_access"],
      allowedPopulations: ["employee"],
    },
    {
      id: "role-supplier-operations",
      applicationId: "app-supplier-portal",
      key: "operations",
      name: "Supplier operations",
      level: "admin",
      permissions: ["supplier.read", "supplier.update", "supplier.manage_access"],
      allowedPopulations: ["employee"],
    },
    {
      id: "role-supplier-partner",
      applicationId: "app-supplier-portal",
      key: "supplier_member",
      name: "Supplier member",
      level: "user",
      permissions: ["supplier.read_own", "supplier.update_own"],
      allowedPopulations: ["external_partner"],
    },
    {
      id: "role-1mwu-member",
      applicationId: "app-1mwu",
      key: "member",
      name: "1MWU member",
      level: "user",
      permissions: ["one_mwu.open"],
      allowedPopulations: ["employee"],
    },
    {
      id: "role-1mwu-admin",
      applicationId: "app-1mwu",
      key: "admin",
      name: "1MWU admin",
      level: "admin",
      permissions: ["one_mwu.open", "one_mwu.manage_access"],
      allowedPopulations: ["employee"],
    },
    {
      id: "role-money-user",
      applicationId: "app-money",
      key: "user",
      name: "Money User",
      level: "user",
      permissions: ["money.read_own", "money.submit"],
      allowedPopulations: ["employee"],
    },
    {
      id: "role-money-admin",
      applicationId: "app-money",
      key: "admin",
      name: "Money Admin",
      level: "admin",
      permissions: ["money.read_own", "money.submit", "money.read_all", "money.review"],
      allowedPopulations: ["employee"],
    },
    {
      id: "role-injuries-user",
      applicationId: "app-injuries",
      key: "user",
      name: "Injury Reporting User",
      level: "user",
      permissions: ["injuries.read_own", "injuries.submit"],
      allowedPopulations: ["employee"],
    },
    {
      id: "role-injuries-admin",
      applicationId: "app-injuries",
      key: "admin",
      name: "Injury Reporting Admin",
      level: "admin",
      permissions: ["injuries.read_own", "injuries.submit", "injuries.read_all", "injuries.review"],
      allowedPopulations: ["employee"],
    },
  ],
  entitlements: [
    {
      id: "entitlement-preview-booking-admin",
      applicationId: "app-booking",
      roleId: "role-booking-admin",
      subject: { type: "user", userId: "user-operations" },
      grantedByUserId: "user-operations",
      grantedAt: "2026-08-17T09:00:00.000Z",
    },
    {
      id: "entitlement-preview-app-builder-admin",
      applicationId: APP_BUILDER_APPLICATION_ID,
      roleId: APP_BUILDER_ADMIN_ROLE_ID,
      subject: { type: "user", userId: "user-operations" },
      grantedByUserId: "user-operations",
      grantedAt: "2026-07-14T16:00:00.000Z",
    },
    {
      id: "entitlement-preview-recruitment-admin",
      applicationId: RECRUITMENT_APPLICATION_ID,
      roleId: RECRUITMENT_ADMIN_ROLE_ID,
      subject: { type: "user", userId: "user-operations" },
      grantedByUserId: "user-operations",
      grantedAt: "2026-07-14T16:00:00.000Z",
    },
    {
      id: "entitlement-preview-superpanel-admin",
      applicationId: SUPERPANEL_APPLICATION_ID,
      roleId: SUPERPANEL_ADMIN_ROLE_ID,
      subject: { type: "user", userId: "user-operations" },
      grantedByUserId: "user-operations",
      grantedAt: "2026-07-01T09:00:00.000Z",
    },
    {
      id: "entitlement-operations-trtl",
      applicationId: "app-trtl",
      roleId: "role-trtl-member",
      subject: { type: "team", teamId: "team-operations" },
      grantedByUserId: "user-operations",
      grantedAt: "2026-07-01T09:00:00.000Z",
    },
    {
      id: "entitlement-insights-answers",
      applicationId: "app-answers",
      roleId: "role-answers-analyst",
      subject: { type: "team", teamId: "team-insights" },
      grantedByUserId: "user-operations",
      grantedAt: "2026-07-01T09:00:00.000Z",
    },
    {
      id: "entitlement-operations-suppliers",
      applicationId: "app-supplier-portal",
      roleId: "role-supplier-operations",
      subject: { type: "team", teamId: "team-operations" },
      scope: { allPartnerOrganisations: true },
      grantedByUserId: "user-operations",
      grantedAt: "2026-07-01T09:00:00.000Z",
    },
    {
      id: "entitlement-operations-1mwu",
      applicationId: "app-1mwu",
      roleId: "role-1mwu-member",
      subject: { type: "team", teamId: "team-operations" },
      grantedByUserId: "user-operations",
      grantedAt: "2026-07-14T16:00:00.000Z",
    },
    {
      id: "entitlement-operations-money",
      applicationId: "app-money",
      roleId: "role-money-admin",
      subject: { type: "team", teamId: "team-operations" },
      grantedByUserId: "user-operations",
      grantedAt: "2026-07-14T16:00:00.000Z",
    },
    {
      id: "entitlement-operations-injuries",
      applicationId: "app-injuries",
      roleId: "role-injuries-admin",
      subject: { type: "team", teamId: "team-operations" },
      grantedByUserId: "user-operations",
      grantedAt: "2026-07-14T16:00:00.000Z",
    },
    {
      id: "entitlement-sunbird-supplier",
      applicationId: "app-supplier-portal",
      roleId: "role-supplier-partner",
      subject: { type: "user", userId: "user-supplier" },
      scope: { partnerOrganisationIds: ["partner-sunbird"] },
      grantedByUserId: "user-operations",
      grantedAt: "2026-07-01T09:00:00.000Z",
    },
  ],
};

export const previewAuditEvents: readonly AuditEvent[] = [
  {
    id: "audit-preview-001",
    occurredAt: "2026-07-14T08:55:00.000Z",
    action: "identity.login",
    outcome: "success",
    actorUserId: "user-operations",
    actorIdentitySubject: previewIdentities.operations.subject,
    requestId: "preview-request-001",
  },
  {
    id: "audit-preview-002",
    occurredAt: "2026-07-14T08:56:00.000Z",
    action: "application.launched",
    outcome: "success",
    actorUserId: "user-operations",
    actorIdentitySubject: previewIdentities.operations.subject,
    applicationId: "app-trtl",
    requestId: "preview-request-002",
  },
];
