"use client";
import Link from "next/link"; import {useMemo,useState} from "react"; import styles from "./initiative-suite.module.css";
const events=[
 {kind:"booking",icon:"BK",title:"Booking confirmed",detail:"BK-19428 moved from option to confirmed",actor:"Maya Chen",time:"09:42",trip:"Wild Coast · 18 Sep",guest:"Amelia Hart"},
 {kind:"guest",icon:"GU",title:"Dietary requirement updated",detail:"Gluten-free preference recorded; operator notified",actor:"Amelia Hart",time:"09:18",trip:"Wild Coast · 18 Sep",guest:"Amelia Hart"},
 {kind:"trip",icon:"TR",title:"Trip notes published",detail:"Arrival briefing v3 shared with 11 booked guests",actor:"Daniel Okafor",time:"Yesterday",trip:"Wild Coast · 18 Sep",guest:"All guests"},
 {kind:"booking",icon:"£",title:"Final balance received",detail:"Payment reconciled against booking BK-19428",actor:"Finance bot",time:"Yesterday",trip:"Wild Coast · 18 Sep",guest:"Amelia Hart"},
 {kind:"trip",icon:"!",title:"Supplier time changed",detail:"Ferry departure moved by 30 minutes; guest notice prepared",actor:"Departure Pulse",time:"16 Jul",trip:"Wild Coast · 18 Sep",guest:"All guests"},
];
export function TrtlActivity(){const [view,setView]=useState("all");const [query,setQuery]=useState("");const visible=useMemo(()=>events.filter(e=>(view==="all"||e.kind===view)&&`${e.title} ${e.detail} ${e.actor} ${e.trip} ${e.guest}`.toLowerCase().includes(query.toLowerCase())),[view,query]);return <main className={styles.shell}><header className={styles.topbar}><Link className={styles.wordmark} href="/">TRTL / ACTIVITY</Link><nav><Link href="/botswarm">BotSwarm</Link><Link href="/systems/control-room">Control room</Link></nav><span className={styles.pill} data-tone="good">Live design</span></header><section className={styles.hero}><span className={styles.eyebrow}>One event · every relevant view</span><h1>Nothing important gets lost.</h1><p>A single trustworthy timeline for every trip, guest and booking—human-readable, permission-aware and linked back to the original record.</p></section><div className={styles.tabs}>{["all","trip","guest","booking"].map(x=><button key={x} data-active={view===x} onClick={()=>setView(x)}>{x[0].toUpperCase()+x.slice(1)} activity</button>)}</div><div className={styles.grid}><section className={`${styles.panel} ${styles.panelWide}`}><header><span className={styles.eyebrow}>Wild Coast · 18 September</span><h2>Activity timeline</h2><input aria-label="Search activity" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search activity, actor or guest…" style={{width:"100%",padding:14,border:"1px solid #ccd7d3",borderRadius:12,background:"white"}}/></header><div className={styles.feed}>{visible.map((e,i)=><article className={styles.feedItem} key={`${e.title}-${i}`}><span className={styles.feedIcon}>{e.icon}</span><div><strong>{e.title}</strong><p>{e.detail}</p><small>{e.actor} · {e.trip} · {e.guest}</small></div><time>{e.time}</time></article>)}</div></section><aside className={styles.panel}><span className={styles.eyebrow}>Feed contract</span><h2>Useful, not invasive.</h2><p>Each event links to its trip, guest and booking once, so every view stays consistent.</p><p>Sensitive before/after values, passports, health data, tokens and raw payloads never enter the feed.</p><p>Airtable imports are labelled as baseline history; they are not presented as a complete audit trail.</p><span className={styles.pill} data-tone="warn">Requires Trtl repository</span></aside></div></main>}
