// Seed/preview data for The Garden, normalised from the real Gardening lists
// supplied on 31 Aug 2026 (Slack user IDs resolved to people the same day).
// Anything the source lists did not state — stages, dates, systems, brands,
// purposes, stand-in owners — is invented for demonstration and recorded in
// demoFields so the UI can say so honestly.

import type { GardenProject, PersonRef } from "./model.ts";

const person = (name: string, email: string | null): PersonRef => ({ id: null, name, email });

// Names and emails resolved against the Notion team directory (31 Aug 2026).
// Nic's Notion email is stale (@patchadventures); the Cove login — and so the
// directory match — is the leatherbacktravel address.
export const NIC = person("Nicola Noviello", "nicola@leatherbacktravel.com");
const COURTNEY = person("Courtney Harman", "courtney@leatherbacktravel.com");
const BRIANA = person("Briana Bessell", "briana@leatherbacktravel.com");
const MADI = person("Madilyn Forster", "madilyn@caminowomen.com.au");
const JUSTIN = person("Justin Kelaher", "justin@patchadventures.com.au");
const RADINA = person("Radina Petrishka", "radina@leatherbacktravel.com");
const JAMIE = person("Jamie Hathaway", "jamie@leatherbacktravel.com");
const NEVENA = person("Nevena Mihajlovic", "nevena@leatherbacktravel.com");
const DIJANA = person("Dijana Blagojevic", "dijana@leatherbacktravel.com");
const KAT = person("Kat Stokes", "kat@leatherbacktravel.com");
const CSILLA = person("Csilla Bozsik", "csilla@leatherbacktravel.com");
const LISA = person("Lisa O'Donnell", "lisa@leatherbacktravel.com");
const CECO = person("Tsvetan Antonov", "tsvetan@leatherbacktravel.com");
const DANE = person("Danko Cimbaljević", "danko@leatherbacktravel.com");
const PIPPA = person("Pippa Chisholm", "pippa@caminowomen.com.au");
const KATARINA = person("Katarina Stanković", "katarina@leatherbacktravel.com");
const DEE = person("Dee Urosevic", "dee@leatherbacktravel.com");
const SOPHIE = person("Sophie Stansfield", "sophie@caminowomen.com.au");
const TEGAN = person("Tegan Weekley", "tegan@patchadventures.com.au");
const MANDY = person("Mandy Scanlon", "mandy@patchadventures.com.au");
const FARRAH = person("Farrah Passmore", "farrah@patchadventures.com.au");
const JANIE = person("Janie Welsh", "janie@leatherbacktravel.com");
const CLAIRE = person("Claire Jakobi", "claire@patchadventures.com.au");
const JAX = person("Jacqueline Lancaster", "jacqueline@carexdesign.com");
const IVANA = person("Ivana Strihic Dojcinovski", "ivana@leatherbacktravel.com");

const pid = (n: number) => `00000000-0000-4000-8000-${String(n).padStart(12, "0")}`;

type SeedInput = Partial<GardenProject> & { id: string; name: string; purpose: string; owner: PersonRef };

const AT_SESSION = "2026-08-24T11:30:00Z";

function project(input: SeedInput): GardenProject {
  return {
    sponsor: null,
    teammates: [],
    growthStage: "In Planning",
    estimatedCompletion: null,
    teams: [],
    systems: [],
    brands: [],
    quarterTheme: null,
    projectLink: null,
    notes: "",
    cancellationReason: null,
    testingOwners: [],
    testingTeams: [],
    relatedProjectIds: [],
    demoFields: [],
    createdAt: AT_SESSION,
    createdBy: null,
    lastEditedAt: AT_SESSION,
    lastEditedBy: null,
    stageChangedAt: AT_SESSION,
    completedAt: null,
    cancelledAt: null,
    archivedAt: null,
    ...input,
  };
}

export const GARDEN_SEED_PROJECTS: GardenProject[] = [
  project({
    id: pid(1),
    name: "Guest Portal",
    purpose: "Give guests one portal for their trip details, documents and pre-departure steps.",
    owner: BRIANA,
    sponsor: COURTNEY,
    growthStage: "Testing or roll out",
    estimatedCompletion: "2026-10-15",
    teams: ["Booking Managers"],
    systems: ["Stacker", "Airtable - Leatherback Bookings and Data base"],
    testingTeams: ["Booking Managers"],
    demoFields: ["purpose", "growthStage", "estimatedCompletion", "systems", "testingTeams"],
  }),
  project({
    id: pid(2),
    name: "TRTL - Stacker replacement",
    purpose: "Replace Stacker with our own Turtle platform before the licence renews.",
    owner: COURTNEY,
    growthStage: "Active work",
    estimatedCompletion: "2026-11-30",
    teams: ["Booking Managers", "Operations"],
    systems: ["Stacker"],
    demoFields: ["purpose", "growthStage", "estimatedCompletion"],
  }),
  project({
    id: pid(3),
    name: "Online Booking Portal",
    purpose: "Let guests book online end-to-end without emailing a Booking Manager.",
    owner: CECO,
    sponsor: COURTNEY,
    growthStage: "Cancelled or replaced",
    teams: ["Operations", "Booking Managers"],
    cancellationReason: "Functionality incorporated into Guest Portal.",
    cancelledAt: "2026-08-24T11:45:00Z",
    stageChangedAt: "2026-08-24T11:45:00Z",
    relatedProjectIds: [pid(1)],
    demoFields: ["purpose", "growthStage", "cancellationReason"],
  }),
  project({
    id: pid(4),
    name: "Today - BM Dashboard",
    purpose: "Give Booking Managers one morning view of calls, departures and flags.",
    owner: NIC,
    growthStage: "Testing or roll out",
    estimatedCompletion: "2026-09-30",
    teams: ["Booking Managers"],
    testingTeams: ["Booking Managers"],
    demoFields: ["purpose", "growthStage", "estimatedCompletion", "testingTeams"],
  }),
  project({
    id: pid(5),
    name: "CallTime - BM Call Scheduling App",
    purpose: "Replace Calendly with our own call scheduling inside Cove.",
    owner: NIC,
    growthStage: "Active work",
    estimatedCompletion: "2026-10-31",
    teams: ["Booking Managers"],
    systems: ["Aircall"],
    demoFields: ["purpose", "growthStage", "estimatedCompletion", "systems"],
  }),
  project({
    id: pid(6),
    name: "Exploring Web Design Capabilities",
    purpose: "Learn what we can build in-house before committing to agency work.",
    owner: NIC,
    growthStage: "Cancelled or replaced",
    cancellationReason: "Exploration complete — learnings folded into the brand website projects.",
    cancelledAt: "2026-07-06T10:00:00Z",
    stageChangedAt: "2026-07-06T10:00:00Z",
    archivedAt: "2026-08-06T10:00:00Z",
    createdAt: "2026-06-01T10:00:00Z",
    lastEditedAt: "2026-07-06T10:00:00Z",
    demoFields: ["purpose", "cancellationReason"],
  }),
  project({
    id: pid(7),
    name: "Automations",
    purpose: "Round up the automations running across our systems.",
    owner: MADI,
    growthStage: "Cancelled or replaced",
    cancellationReason: "Superseded by the Automations Index project.",
    cancelledAt: "2026-07-13T10:00:00Z",
    stageChangedAt: "2026-07-13T10:00:00Z",
    archivedAt: "2026-08-13T10:00:00Z",
    createdAt: "2026-06-01T10:00:00Z",
    lastEditedAt: "2026-07-13T10:00:00Z",
    relatedProjectIds: [pid(15)],
    demoFields: ["purpose", "cancellationReason"],
  }),
  project({
    id: pid(8),
    name: "The Helm - Pod Lead Dashboard",
    purpose: "Give pod leads a single dashboard of their pod's numbers.",
    owner: JUSTIN,
    growthStage: "Cancelled or replaced",
    cancellationReason: "Replaced by the Pod Lead Dashboards / Databox work.",
    cancelledAt: "2026-08-24T11:50:00Z",
    stageChangedAt: "2026-08-24T11:50:00Z",
    relatedProjectIds: [pid(21)],
    demoFields: ["purpose", "cancellationReason"],
  }),
  project({
    id: pid(9),
    name: "New Supplier Portal",
    purpose: "Build suppliers a portal for availability, rates and trip information.",
    owner: RADINA,
    growthStage: "Active work",
    estimatedCompletion: "2026-12-15",
    teams: ["DMC"],
    demoFields: ["purpose", "growthStage", "estimatedCompletion"],
  }),
  project({
    id: pid(10),
    name: "Nest - TD Airtable replacement",
    purpose: "Move Trip Design off its overloaded Airtable base and into Nest.",
    owner: JAMIE,
    growthStage: "Active work",
    estimatedCompletion: "2026-11-15",
    teams: ["Trip Design"],
    systems: ["Airtable - Trip Design base"],
    demoFields: ["purpose", "growthStage", "estimatedCompletion", "systems"],
  }),
  project({
    id: pid(11),
    name: "Toucan - Flamingo replacement",
    purpose: "Replace Flamingo with our own team portal.",
    owner: NEVENA,
    sponsor: NIC,
    growthStage: "Active work",
    estimatedCompletion: "2026-10-31",
    teams: ["HR & Hiring"],
    systems: ["Flamingo"],
    demoFields: ["purpose", "growthStage", "estimatedCompletion", "systems"],
  }),
  project({
    id: pid(12),
    name: "Octomancer",
    purpose: "Automate our multi-channel content publishing tentacles.",
    owner: DIJANA,
    growthStage: "Active work",
    teams: ["Marketing"],
    demoFields: ["purpose", "growthStage", "teams"],
  }),
  project({
    id: pid(13),
    name: "HelpScout Side Panel",
    purpose: "Show booking context beside every HelpScout conversation.",
    owner: KAT,
    growthStage: "Active work",
    estimatedCompletion: "2026-09-30",
    teams: ["Booking Managers", "Operations"],
    systems: ["HelpScout - Adventure Brands"],
    demoFields: ["purpose", "growthStage", "estimatedCompletion", "systems"],
  }),
  project({
    id: pid(14),
    name: "Trip Coord Pod Interface Replacement",
    purpose: "Rebuild the Trip Coordination pod's day-to-day interface.",
    owner: MADI,
    growthStage: "Active work",
    teams: ["Booking Managers", "Operations"],
    systems: ["Airtable - Daily Operations base"],
    demoFields: ["purpose", "growthStage", "systems"],
  }),
  project({
    id: pid(15),
    name: "Automations Index",
    purpose: "Keep one searchable index of every automation we run.",
    owner: MADI,
    growthStage: "Active work",
    systems: ["Zapier"],
    demoFields: ["purpose", "growthStage", "systems"],
  }),
  project({
    id: pid(16),
    name: "Brand Pod Interface Replacement",
    purpose: "Rebuild the Brand pod's working interface.",
    owner: MADI,
    growthStage: "Active work",
    demoFields: ["purpose", "growthStage"],
  }),
  project({
    id: pid(17),
    name: "Invoice Generator",
    purpose: "Generate trip invoices automatically instead of by hand.",
    owner: BRIANA,
    growthStage: "Active work",
    teams: ["Booking Managers", "Operations"],
    systems: ["Xero"],
    demoFields: ["purpose", "growthStage", "systems"],
  }),
  project({
    id: pid(18),
    name: "Guide training course",
    purpose: "Build a training course for new trip guides.",
    owner: LISA,
    teams: ["Trip Design"],
    createdAt: "2026-05-10T10:00:00Z",
    lastEditedAt: "2026-05-10T10:00:00Z",
    stageChangedAt: "2026-05-10T10:00:00Z",
    demoFields: ["purpose", "owner"],
  }),
  project({
    id: pid(19),
    name: "Pricing Process",
    purpose: "Standardise how trips are priced and reviewed.",
    owner: CSILLA,
    teams: ["Trip Design"],
    notes: "Working doc lives in Airtable.",
    demoFields: ["purpose"],
  }),
  project({
    id: pid(20),
    name: "Debut Trips",
    purpose: "Smooth the path from a new trip idea to its first departure.",
    owner: LISA,
    growthStage: "Active work",
    estimatedCompletion: "2026-08-15",
    teams: ["Trip Design"],
    createdAt: "2026-06-15T10:00:00Z",
    lastEditedAt: "2026-07-20T10:00:00Z",
    stageChangedAt: "2026-07-20T10:00:00Z",
    demoFields: ["purpose", "growthStage", "estimatedCompletion"],
  }),
  project({
    id: pid(21),
    name: "Pod Lead Dashboards / Databox",
    purpose: "Give pod leads live numbers through Databox dashboards.",
    owner: JUSTIN,
    sponsor: NIC,
    growthStage: "Active work",
    teams: ["Finance"],
    systems: ["Databox"],
    demoFields: ["purpose", "owner", "growthStage", "systems"],
  }),
  project({
    id: pid(22),
    name: "Brianna's risk and ops work / incident management",
    purpose: "Integrate risk assessment and incident management into daily operations.",
    owner: BRIANA,
    teams: ["Trip Design"],
    demoFields: ["purpose", "owner"],
  }),
  project({
    id: pid(23),
    name: "Survey our suppliers",
    purpose: "Ask suppliers how working with us could be smoother.",
    owner: JAMIE,
    teams: ["Trip Design"],
    demoFields: ["purpose", "owner"],
  }),
  project({
    id: pid(24),
    name: "Distribute the unicorn prizes",
    purpose: "Get the unicorn prizes into winners' hands.",
    owner: LISA,
    growthStage: "Complete",
    teams: ["Trip Design"],
    completedAt: "2026-08-20T10:00:00Z",
    stageChangedAt: "2026-08-20T10:00:00Z",
    lastEditedAt: "2026-08-20T10:00:00Z",
    demoFields: ["purpose", "owner", "growthStage"],
  }),
  project({
    id: pid(25),
    name: "Hotel night management - Portal & AI",
    purpose: "Manage extra hotel nights through the portal with AI assistance.",
    owner: KAT,
    teams: ["Operations"],
    demoFields: ["purpose", "owner"],
  }),
  project({
    id: pid(26),
    name: "Flag guests emailing within 72 hrs of trip start",
    purpose: "Route imminent-departure guest emails straight into Trip Help.",
    owner: NEVENA,
    growthStage: "Active work",
    estimatedCompletion: "2026-09-15",
    teams: ["Operations"],
    systems: ["HelpScout - Adventure Brands", "Slack Workspace - Leatherback Travel"],
    demoFields: ["purpose", "estimatedCompletion", "systems"],
  }),
  project({
    id: pid(27),
    name: "Check nationality against visa requirements",
    purpose: "Catch visa problems before guests reach the airport.",
    owner: DANE,
    teams: ["Operations"],
    demoFields: ["purpose", "owner"],
  }),
  project({
    id: pid(28),
    name: "AI: Meet your trip mate in the portal",
    purpose: "Introduce guests to their trip mates inside the portal.",
    owner: BRIANA,
    teams: ["Operations"],
    demoFields: ["purpose", "owner"],
  }),
  project({
    id: pid(29),
    name: "Guest refund revamp",
    purpose: "Make guest refunds faster and less manual.",
    owner: DANE,
    teammates: [PIPPA],
    teams: ["Operations", "Booking Managers"],
    demoFields: ["purpose"],
  }),
  project({
    id: pid(30),
    name: "Picking up more BM email",
    purpose: "Shift more Booking Manager email into shared handling.",
    owner: CSILLA,
    teammates: [NEVENA],
    sponsor: COURTNEY,
    growthStage: "Active work",
    teams: ["Operations"],
    projectLink: "https://patchadventures.slack.com/docs/T03S41T12NP/F0BJ2SL35UL",
    demoFields: ["purpose"],
  }),
  project({
    id: pid(31),
    name: "FILL RATES - advanced modelling",
    purpose: "Model fill rates by cohort and develop the metrics behind them.",
    owner: COURTNEY,
    quarterTheme: "Gnarly Oozes",
    teams: ["Finance"],
    demoFields: ["purpose", "owner"],
  }),
  project({
    id: pid(32),
    name: "Financial Control - Salemi and Garrigue integration",
    purpose: "Bring Salemi and Garrigue fully into our financial controls.",
    owner: COURTNEY,
    teams: ["Finance"],
    systems: ["Xero"],
    demoFields: ["purpose", "owner", "systems"],
  }),
  project({
    id: pid(33),
    name: "FILL RATES - AI generated marketing segments",
    purpose: "Turn fill-rate data into AI-generated marketing segments.",
    owner: KATARINA,
    quarterTheme: "Gnarly Oozes",
    teams: ["Marketing"],
    demoFields: ["purpose", "owner"],
  }),
  project({
    id: pid(34),
    name: "Mailvio rollout - migrate other brands onto Mailvio",
    purpose: "Move remaining brands onto Mailvio and standardise email marketing.",
    owner: KATARINA,
    growthStage: "Active work",
    estimatedCompletion: "2026-10-31",
    teams: ["Marketing"],
    systems: ["Mailvio"],
    brands: ["Camino Women", "Fencox Travel", "Carex Garden Tours"],
    demoFields: ["purpose", "growthStage", "estimatedCompletion", "brands"],
  }),
  project({
    id: pid(35),
    name: "Rollout Trip Highlights improvement",
    purpose: "Roll the improved Trip Highlights format out across brands.",
    owner: DIJANA,
    teams: ["Marketing"],
    demoFields: ["purpose", "owner"],
  }),
  project({
    id: pid(36),
    name: "Magex website refresh",
    purpose: "Refresh the Magnificent Explorers website.",
    owner: KATARINA,
    sponsor: JUSTIN,
    teams: ["Marketing"],
    brands: ["Magnificent Explorers"],
    demoFields: ["purpose", "owner", "brands"],
  }),
  project({
    id: pid(37),
    name: "Fencox brand refresh",
    purpose: "Refresh the Fencox Travel brand identity.",
    owner: DIJANA,
    sponsor: JUSTIN,
    growthStage: "Active work",
    estimatedCompletion: "2026-11-30",
    teams: ["Marketing"],
    systems: ["Webflow"],
    brands: ["Fencox Travel"],
    demoFields: ["purpose", "owner", "growthStage", "estimatedCompletion", "systems", "brands"],
  }),
  project({
    id: pid(38),
    name: "PR firm onboarding",
    purpose: "Bring the new PR firm up to speed on our brands.",
    owner: KATARINA,
    sponsor: COURTNEY,
    teams: ["Marketing"],
    demoFields: ["purpose", "owner"],
  }),
  project({
    id: pid(39),
    name: "Leatherback DMC Pages",
    purpose: "Publish pages presenting our DMC capabilities.",
    owner: RADINA,
    teams: ["Marketing"],
    demoFields: ["purpose", "owner"],
  }),
  project({
    id: pid(40),
    name: "Leatherback Digital PR - Trackability and Targeting",
    purpose: "Make digital PR spend trackable and better targeted.",
    owner: JUSTIN,
    teams: ["Marketing"],
    demoFields: ["purpose", "owner"],
  }),
  project({
    id: pid(41),
    name: "AI: DMC Systems starts to build them V1",
    purpose: "Start building the DMC's core systems with AI assistance.",
    owner: RADINA,
    teams: ["DMC"],
    demoFields: ["purpose", "owner"],
  }),
  project({
    id: pid(42),
    name: "Local Moments - Design and Manage",
    purpose: "Design and manage the Local Moments experiences.",
    owner: RADINA,
    teams: ["DMC"],
    demoFields: ["purpose", "owner"],
  }),
  project({
    id: pid(43),
    name: "Team ENPS score",
    purpose: "Measure and track team ENPS regularly.",
    owner: DEE,
    teammates: [CSILLA],
    sponsor: NIC,
    growthStage: "Active work",
    teams: ["HR & Hiring"],
    demoFields: ["purpose", "growthStage"],
  }),
  project({
    id: pid(44),
    name: "ToG",
    purpose: "Shape the ToG programme and get it moving.",
    owner: PIPPA,
    teammates: [SOPHIE],
    sponsor: COURTNEY,
    teams: ["Leadership"],
    demoFields: ["purpose", "teams"],
  }),
  project({
    id: pid(45),
    name: "Extensions",
    purpose: "Standardise how trip extensions are quoted, booked and communicated.",
    owner: TEGAN,
    teammates: [MANDY, FARRAH],
    sponsor: COURTNEY,
    growthStage: "Active work",
    teams: ["Operations", "Booking Managers"],
    systems: ["Stacker", "Payment Code and FAQ Extractor"],
    notes: "SOP/info page; what info is in Stacker; sending res emails using the FAQ extractor; getting deposit amounts.",
    demoFields: ["purpose", "growthStage"],
  }),
  project({
    id: pid(46),
    name: "Saved Replies/Notion refresh",
    purpose: "Move saved replies to where each team actually works.",
    owner: SOPHIE,
    sponsor: COURTNEY,
    growthStage: "Active work",
    teams: ["Operations", "Booking Managers"],
    systems: ["Notion - Leatherback Travel", "HelpScout - Adventure Brands"],
    notes: "Move less-used BM saved replies to Notion (meatballs); move common ops replies to HelpScout.",
    demoFields: ["purpose", "growthStage"],
  }),
  project({
    id: pid(47),
    name: "Trip Summaries",
    purpose: "Move trip summaries from Notion into Stacker.",
    owner: JANIE,
    teammates: [KAT, CLAIRE],
    sponsor: NIC,
    growthStage: "Active work",
    estimatedCompletion: "2026-11-15",
    teams: ["Booking Managers"],
    systems: ["Notion - Leatherback Travel", "Stacker"],
    notes: "Trip Summaries Notion → Stacker.",
    demoFields: ["purpose", "growthStage", "estimatedCompletion"],
  }),
  project({
    id: pid(48),
    name: "Booking Cutoff Process",
    purpose: "Set one clear booking cutoff process across brands.",
    owner: CLAIRE,
    sponsor: COURTNEY,
    teams: ["Booking Managers"],
    demoFields: ["purpose"],
  }),
  project({
    id: pid(49),
    name: "Optimising call summaries",
    purpose: "Improve call summaries towards hands-off activity feeds.",
    owner: KAT,
    teammates: [JAX],
    sponsor: NIC,
    growthStage: "Active work",
    teams: ["Booking Managers"],
    systems: ["Aircall"],
    notes: "Long-term aim: a hands-off automation maintaining activity feeds.",
    demoFields: ["purpose", "growthStage", "teams", "systems"],
  }),
  project({
    id: pid(50),
    name: "Lead tidy-up",
    purpose: "Tidy the lead pipeline before the 2027 season.",
    owner: NIC,
    teammates: [BRIANA],
    sponsor: NIC,
    growthStage: "Active work",
    teams: ["Booking Managers"],
    notes: "Lead Tidy-Up Project 2026.",
    demoFields: ["purpose", "growthStage", "teams"],
  }),
  project({
    id: pid(51),
    name: "New Process Rollouts",
    purpose: "Give every new process a consistent rollout path.",
    owner: COURTNEY,
    sponsor: COURTNEY,
    growthStage: "Active work",
    teams: ["Leadership"],
    demoFields: ["purpose", "growthStage"],
  }),
  project({
    id: pid(52),
    name: "TD technical support and CI",
    purpose: "Give Trip Design steady technical support and continuous improvement.",
    owner: CSILLA,
    growthStage: "Active work",
    teams: ["Trip Design"],
    systems: ["HelpScout - Trip Design"],
    notes: "HelpScout inboxes; trip invoices and comms; tidying the AT base; proofreading workflow.",
    demoFields: ["purpose", "growthStage", "systems"],
  }),
  project({
    id: pid(53),
    name: "Channel triage bot",
    purpose: "Triage busy channels so the right people see the right messages.",
    owner: CSILLA,
    teammates: [IVANA],
    sponsor: COURTNEY,
    growthStage: "Active work",
    estimatedCompletion: "2026-09-30",
    teams: ["Operations"],
    systems: ["Slack Workspace - Leatherback Travel"],
    notes: "Ops notifications; BM notifications; ask system.",
    demoFields: ["purpose", "growthStage", "estimatedCompletion", "systems"],
  }),
  project({
    id: pid(54),
    name: "AT Naming Configuration",
    purpose: "Agree one naming configuration across our Airtable bases.",
    owner: CSILLA,
    teammates: [NEVENA],
    teams: ["Operations"],
    systems: ["Airtable - Daily Operations base"],
    demoFields: ["purpose", "teams", "systems"],
  }),
  project({
    id: pid(55),
    name: "Fit to Explore - Fit and Fitness customer journey review",
    purpose: "Review how fitness expectations flow through the whole guest journey.",
    owner: JUSTIN,
    sponsor: JUSTIN,
    teams: ["Operations", "Trip Design", "Booking Managers", "Marketing"],
    demoFields: ["purpose"],
  }),
  project({
    id: pid(56),
    name: "Fencox new website",
    purpose: "Build the new Fencox Travel website.",
    owner: JUSTIN,
    sponsor: JUSTIN,
    growthStage: "Active work",
    estimatedCompletion: "2026-12-15",
    teams: ["Marketing"],
    systems: ["Webflow"],
    brands: ["Fencox Travel"],
    demoFields: ["purpose", "growthStage", "estimatedCompletion", "teams", "systems", "brands"],
  }),
  project({
    id: pid(57),
    name: "Headless CMS development & implementation",
    purpose: "Move brand sites onto a headless CMS. (Needs a new name!)",
    owner: CECO,
    growthStage: "Active work",
    teams: ["Marketing"],
    systems: ["Wordpress", "Webflow"],
    demoFields: ["purpose", "growthStage", "teams", "systems"],
  }),
  project({
    id: pid(58),
    name: "Implementing Marketing Intensive outcomes",
    purpose: "Turn the Marketing Intensive's outcomes into shipped changes.",
    owner: COURTNEY,
    quarterTheme: "Chop Chop",
    teams: ["Marketing"],
    demoFields: ["purpose", "owner", "teams", "quarterTheme"],
  }),
  project({
    id: pid(59),
    name: "Implementing Aussie Hackathon outcomes",
    purpose: "Turn the Aussie Hackathon's outcomes into shipped changes.",
    owner: NIC,
    quarterTheme: "Chop Chop",
    teams: ["Leadership"],
    demoFields: ["purpose", "owner", "teams", "quarterTheme"],
  }),
];
