import React from "react";
import { ClerkProvider } from "@clerk/nextjs";
import { assertHttpUrl, cleanString } from "./core.js";

export function getCoveProviderProps(overrides = {}) {
  const {
    primaryUrl: primaryUrlOverride,
    signInUrl: signInUrlOverride,
    signUpUrl: signUpUrlOverride,
    publishableKey: publishableKeyOverride,
    domain: _legacyDomain,
    isSatellite: _legacyIsSatellite,
    satelliteAutoSync: _legacySatelliteAutoSync,
    ...clerkProps
  } = overrides;
  const primaryUrl = cleanString(primaryUrlOverride) || cleanString(process.env.NEXT_PUBLIC_COVE_PRIMARY_URL);
  const signInUrl = cleanString(signInUrlOverride) || cleanString(process.env.NEXT_PUBLIC_CLERK_SIGN_IN_URL) ||
    (primaryUrl ? new URL("/sign-in", assertHttpUrl(primaryUrl, "NEXT_PUBLIC_COVE_PRIMARY_URL")).toString() : undefined);
  const signUpUrl = cleanString(signUpUrlOverride) || cleanString(process.env.NEXT_PUBLIC_CLERK_SIGN_UP_URL) || signInUrl;
  const publishableKey = cleanString(publishableKeyOverride) || cleanString(process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY);

  return {
    ...clerkProps,
    ...(publishableKey ? { publishableKey } : {}),
    ...(signInUrl ? { signInUrl } : {}),
    ...(signUpUrl ? { signUpUrl } : {}),
  };
}

// Compatibility alias for applications generated by Cove Auth 1.0.
// It deliberately returns shared parent-domain configuration.
export const getCoveSatelliteProviderProps = getCoveProviderProps;

export function CoveClerkProvider({ children, ...overrides }) {
  return React.createElement(
    ClerkProvider,
    getCoveProviderProps(overrides),
    children,
  );
}
