import { clerkMiddleware, createRouteMatcher } from "@clerk/nextjs/server";
import { assertHttpUrl, cleanString } from "./core.js";

export const DEFAULT_PUBLIC_ROUTES = Object.freeze([
  "/.well-known/cove-access(.*)",
  "/api/cove-auth/health(.*)",
  "/_next(.*)",
  "/favicon.ico",
]);

export function createCoveProtectedRoute(patterns) {
  if (!Array.isArray(patterns) || patterns.length === 0) {
    throw new TypeError("createCoveProtectedRoute requires at least one route pattern.");
  }
  return createRouteMatcher(patterns);
}

export function getCoveMiddlewareOptions(overrides = {}) {
  const {
    primaryUrl: primaryUrlOverride,
    signInUrl: signInUrlOverride,
    signUpUrl: signUpUrlOverride,
    publishableKey: publishableKeyOverride,
    secretKey: secretKeyOverride,
    domain: _legacyDomain,
    isSatellite: _legacyIsSatellite,
    satelliteAutoSync: _legacySatelliteAutoSync,
    publicRoutes: _publicRoutes,
    protectedRoutes: _protectedRoutes,
    ...clerkOptions
  } = overrides;
  const primaryUrl = cleanString(primaryUrlOverride) || cleanString(process.env.COVE_PRIMARY_URL) || cleanString(process.env.NEXT_PUBLIC_COVE_PRIMARY_URL);
  const signInUrl = cleanString(signInUrlOverride) || cleanString(process.env.NEXT_PUBLIC_CLERK_SIGN_IN_URL) ||
    (primaryUrl ? new URL("/sign-in", assertHttpUrl(primaryUrl, "COVE_PRIMARY_URL")).toString() : undefined);
  const signUpUrl = cleanString(signUpUrlOverride) || cleanString(process.env.NEXT_PUBLIC_CLERK_SIGN_UP_URL) || signInUrl;

  return {
    ...clerkOptions,
    ...(signInUrl ? { signInUrl } : {}),
    ...(signUpUrl ? { signUpUrl } : {}),
    ...(cleanString(publishableKeyOverride) ? { publishableKey: cleanString(publishableKeyOverride) } : {}),
    ...(cleanString(secretKeyOverride) ? { secretKey: cleanString(secretKeyOverride) } : {}),
  };
}

// Compatibility alias for applications generated by Cove Auth 1.0.
export const getCoveSatelliteMiddlewareOptions = getCoveMiddlewareOptions;

export function createCoveProxy(options = {}) {
  const publicRoute = createRouteMatcher(options.publicRoutes || DEFAULT_PUBLIC_ROUTES);
  const protectedRoute = options.protectedRoutes
    ? createCoveProtectedRoute(options.protectedRoutes)
    : (request) => !publicRoute(request);

  const middlewareOptions = getCoveMiddlewareOptions(options);
  return clerkMiddleware(async (auth, request) => {
    if (!protectedRoute(request)) return;
    const session = await auth();
    if (!session.userId) {
      return session.redirectToSignIn({ returnBackUrl: request.url });
    }
  }, middlewareOptions);
}

export const COVE_PROXY_MATCHER = Object.freeze([
  "/((?!_next/static|_next/image|favicon.ico|sitemap.xml|robots.txt|.*\\.(?:html?|css|js(?!on)|jpe?g|webp|png|gif|svg|ttf|woff2?|ico|csv|docx?|xlsx?|zip|webmanifest)).*)",
  "/(api|trpc)(.*)",
  "/__clerk/(.*)",
]);
