import type { Brand } from "./model";

// Generated from Leatherback Brands & Legal Setup → Brand Overviews.
// Public brand descriptions supplement fields that are not held in Airtable.
export const airtableBrandSnapshot: Brand[] = [
  {
    "id": "recW7ukep5G1SzBze",
    "name": "Camino Women",
    "description": "Walking adventures for women, pairing memorable trails with deeper cultural experiences.",
    "category": "Brand overview",
    "region": "Leatherback network",
    "website": "https://caminowomen.com.au",
    "instagram": "https://www.instagram.com/caminowomenig/",
    "facebook": "https://www.facebook.com/caminowomenfb",
    "brandFilesUrl": "https://drive.google.com/drive/folders/1J2mmA5YJLydq7TyF0cjbzE38BDbT9uF5?usp=share_link",
    "brandFilesLabel": "Brand files",
    "brandGuidelinesUrl": "https://drive.google.com/drive/folders/1olZ0lIqfCL44FjbrF8nwTGiNQT6Ppvtw?usp=sharing",
    "productBriefUrl": "https://docs.google.com/document/d/1Lz_6CJTTOcupgYuT0XfwsWekjgQe4F05NYlBpsjjWII/edit?usp=share_link",
    "brandColours": "Main Colour: 295244 (Green); ",
    "registrationStatus": "Registered",
    "legalEntityOwner": "Leatherback Travel Pty Ltd\n",
    "logoUrl": "https://v5.airtableusercontent.com/v3/u/55/55/1784059200000/mYGk_y60iRQUiSboqBHdVA/cTz0fXVwSgguJcYPMCYWHyZLiixeDEBI8_twb_uQeaCT2rqwWlpC365OnBtqrhgneSl1gRRqVihSkA9Tq0PtdwMWBHcVm2CgZNfhcf9VtPgS6xDGw0gatwy8aK5qB5Zen6Kq3Ei4XkL3UB1y0fNX_T3LVaAhpOYZoPfD0_1XL_IH6pOKBB_IYEj_uHHVcjbK/w_RTweOWqWeUanLeBBOqdGhHrNlx734hggKmxLc5yIo",
    "logoTone": "dark",
    "status": "active",
    "accent": "#295244"
  },
  {
    "id": "recrf50swy5ulNXjp",
    "name": "Carex Design Tours",
    "description": "Expert-led garden journeys blending horticulture, culture, creativity and nature.",
    "category": "Brand overview",
    "region": "Leatherback network",
    "website": "https://www.carexdesign.com/",
    "instagram": "https://www.instagram.com/carextours/",
    "facebook": "https://www.facebook.com/carexdesigntours/",
    "brandFilesUrl": "https://drive.google.com/drive/folders/1jttKO-5vJp-4_5RvxyBpcIOy_T2LOwmF",
    "brandFilesLabel": "Brand files",
    "brandGuidelinesUrl": "https://drive.google.com/file/d/1FmCiLMf31G38uQW8DTIaOrng4IN9GpFS/view?usp=drive_link",
    "productBriefUrl": "https://docs.google.com/document/d/18t-r2UW-yoLY1UBPkpRPXt97zrJfmxoFOCrUJOeNPlg/edit?tab=t.0",
    "brandColours": "Main Colours: \n#005857 (Dark Green) \n#fcb034 (Sunny Orange)\n",
    "registrationStatus": "Registered",
    "legalEntityOwner": "Carex Garden Tours LLC",
    "logoUrl": "https://v5.airtableusercontent.com/v3/u/55/55/1784059200000/5A6r2zB-EettUKNsCeqwvA/NyRNnJS7talIOJOpc0qYD6aQmMiIGahzChnngecT9M5R27tDprbGwU4KEeCyBDouttUrAYomhhBtJSFMh3HLJ0RjI8EMzOuRW0VezXDhaVa_sSoZFYppyS5JlFwBLjN0LFQCthJ30GCpUxwsjFi5veedT0AERIVWBB1nwUXzeMlzbWiCtB7kSLIMNwwcYD36A-7_saZWA_OMSunN3YRNkw/MKpxPAMsihEk_VLVkt2C2wg4RZaqNWr0J6k3yKMLvq8",
    "logoTone": "dark",
    "status": "active",
    "accent": "#005857"
  },
  {
    "id": "recr23nLijnSBYwBB",
    "name": "Club Garrigue",
    "description": "An early-stage brand record currently moving through setup.",
    "category": "Brand overview",
    "region": "Leatherback network",
    "brandFilesLabel": "Brand files",
    "registrationStatus": "Not Registered",
    "legalEntityOwner": "PLANNED - Club Garrigue LLC -> Owned by Leatherback Holdings Pty Ltd",
    "logoTone": "dark",
    "status": "developing",
    "accent": "#0b8b84"
  },
  {
    "id": "rec4OpqNoJhE4kGuk",
    "name": "Fencox Travel",
    "description": "Small-group cultural travel for solo adventurers, with private-room options at the heart of the experience.",
    "category": "Brand overview",
    "region": "Leatherback network",
    "website": "https://fencox.com.au",
    "instagram": "https://www.instagram.com/fencoxtravel/",
    "facebook": "https://www.facebook.com/fencoxtravel",
    "brandFilesUrl": "https://drive.google.com/drive/folders/1idqXcnkL6tUNNRz-EBtL3pBmKyPHr8sL?usp=share_link",
    "brandFilesLabel": "Brand files",
    "brandGuidelinesUrl": "https://drive.google.com/drive/folders/16gUKJ9eys53VaR0fHiKi43Ys2Su0MHRO?usp=share_link",
    "productBriefUrl": "https://docs.google.com/document/d/119vd698EB96oLviSIPepiqZ0S3uU45ZZWpgcSGr5p-M/edit?usp=share_link",
    "brandColours": "Main Colours: 004C7A (Dark Blue) ; #F7F5F2 (white)",
    "registrationStatus": "Registered",
    "legalEntityOwner": "Leatherback Travel Pty Ltd",
    "logoUrl": "https://v5.airtableusercontent.com/v3/u/55/55/1784059200000/RhAGGCi7YMH81CR-MXxl6g/Q-UTHD27vc7vKqPtrzgSdSQc-G041vKbI95-eQGvfSL4dPqAc7KWx8muTDRw46mlkEycANiAuJvmWPQJV-kdNfsves1eDtmSRnwwkVptAvZdvK44CxUxhGW3WZJgA3BLqMMBcgHc5N0WIrCdc5AkZNKm2F4riDPCmJ-JVnQOTIA/ZuhSW9fIrS6osgDqb7SNSoI95e79RMyIZiDyB1WiXR4",
    "logoTone": "dark",
    "status": "active",
    "accent": "#004C7A"
  },
  {
    "id": "rec2SEMnNnXiDbN0X",
    "name": "Harriet Adventures",
    "description": "A developing travel brand with its identity, channels and core brand documents connected in Airtable.",
    "category": "Brand overview",
    "region": "Leatherback network",
    "website": "https://harrietadventures.com/",
    "instagram": "https://www.instagram.com/travelwithharrietadventures/",
    "facebook": "https://www.facebook.com/HarrietAdventures",
    "brandFilesUrl": "https://drive.google.com/drive/folders/1cYR2C5Kwn8l5JXS0QBGrjLSfbBVCvjx6",
    "brandFilesLabel": "Brand files",
    "productBriefUrl": "https://docs.google.com/document/d/1yldQ_zOzkJbJmNeSI6xd6vMjoqPIEGLfXxenpygTXrE/edit?usp=drive_link",
    "brandColours": "#466e93 (Blue)\n#e6b45a (Yellow)\n#e0594f (Red accent colour)",
    "registrationStatus": "Not Registered",
    "legalEntityOwner": "PLANNED - Harriet Adventures LLC -> Leatherback Travel  Pty Ltd",
    "logoUrl": "https://v5.airtableusercontent.com/v3/u/55/55/1784059200000/VhawEzibL7zlsrGxhBljPQ/Itdomeyg7dcd0t09UMC8nMke39pyOgIi8XsO7I5BRdCnE6IBuXs5bdK2LPhK9AwRCZNK9AmrVr5w46hCCahbsjpCULNQ1G4ECd2wPeVTg5MaSH2Z1Ae7O_gxhCyJBU7MmikOliMs0q4uorxnzWdllq8mg3XsW-l9bAM4S3ea2tWn1c3pa9F8_YwsIDYiTxlb/py0KlePbYoAayR1XGoBEMhmyvVP5-mfH6jpe1ElBQuQ",
    "logoTone": "dark",
    "status": "developing",
    "accent": "#466e93"
  },
  {
    "id": "recdtb2ayJTlnnm5d",
    "name": "Magnificent Rail",
    "description": "Small-group cultural rail journeys designed to go beyond the obvious.",
    "category": "Brand overview",
    "region": "Leatherback network",
    "website": "https://magnificentrail.com.au",
    "instagram": "https://www.instagram.com/magnificentrail/",
    "facebook": "https://www.facebook.com/magnificentrail",
    "brandFilesUrl": "https://drive.google.com/drive/folders/1iETZX9wBWMaWZAx9_1XxOtw04DE7Sv7Z?usp=share_link",
    "brandFilesLabel": "Brand files",
    "brandGuidelinesUrl": "https://drive.google.com/drive/folders/1V0AP-xjxLBdJ7NpqtcsTUuega27S7H5T?usp=share_link",
    "productBriefUrl": "https://docs.google.com/document/d/1rz4uTcA8gOsT0mfCWWAkf25T0JOjMYkmWf3PpWG9ycQ/edit?usp=sharing",
    "brandColours": "Main Colours: 1B2A3B (Dark Navy Blue); C47B52 (Dark Orange); EDAE81 (Light Orange); FF002E (White)",
    "registrationStatus": "Registered",
    "legalEntityOwner": "Shoebill Travel Pty Ltd",
    "logoUrl": "https://v5.airtableusercontent.com/v3/u/55/55/1784059200000/EWA8-KEj6XleOvkdf_aBTA/sV5pBpmmGmU-LLhjvx0FfAiIYotv80t3eZfeUcVpn5SHvV4s0vc2oWIiS7d9wB_guD9Q_jEIe6T-XlWzkd3JFcaO4hUzLmCjctKQQm5KT-gmd7-t86nWaBHLPwRXWKQFRCpZbfMyXrSg2Vit09bLERwWiAPFai5cnOH1TZGuIcI/lTadQA5WJQjz_PUlA20Z6gJUcpmUj2OxiuWMV0UFqWM",
    "logoTone": "dark",
    "status": "active",
    "accent": "#1B2A3B"
  },
  {
    "id": "recHL85UeFVsFiP5i",
    "name": "Patch Adventures",
    "description": "Women-only cultural adventures to less-explored corners of the world, built around connection and discovery.",
    "category": "Brand overview",
    "region": "Leatherback network",
    "website": "https://patchadventures.com.au",
    "instagram": "https://www.instagram.com/patchadventures/",
    "facebook": "https://www.facebook.com/patchadventures/",
    "brandFilesUrl": "https://drive.google.com/drive/folders/1iETZX9wBWMaWZAx9_1XxOtw04DE7Sv7Z?usp=share_link",
    "brandFilesLabel": "Brand files",
    "brandGuidelinesUrl": "https://drive.google.com/drive/folders/15Urc5X-FrsrK6jnmYWFW_SccX3W26GF8?usp=share_link",
    "productBriefUrl": "https://docs.google.com/document/d/1gnNY4-aDTXVSrMCZUILRzbC4yuQmTKsKEOIQiX6I1B0/edit?usp=share_link",
    "brandColours": "Main Colour: Color-patch: rgba(173, 80, 70, 1);  -- #ad5046;",
    "registrationStatus": "Registered",
    "legalEntityOwner": "Leatherback Travel Pty Ltd",
    "logoUrl": "https://v5.airtableusercontent.com/v3/u/55/55/1784059200000/2dHWBUb13hdOA6CKtSmFWg/LI0ZszdmTakNLrMj4GSIRxZKb2QVjpEpRXX7QnYidekbW2nSUaVNiXCUSOtsCzO0Gpmn-XgiLrOZ_wj3e4e_DRCeSAsy-ubbhkCSL_skhh6LdNfSp7kFIWuLoY79aCtgBtOhbxhuJRDXQPBXLQF3OQe2ajxhrmbiV4ouetrHo_YAW_b-bfJUQg0L2d62mQEr/SIXq5on1yY2WIrpGUCxS0pFT2E8AFAS-QxTJt-XEoUs",
    "logoTone": "dark",
    "status": "active",
    "accent": "#ad5046"
  },
  {
    "id": "rec1vN7DBMOM2jcqa",
    "name": "Salemi Ceramics",
    "description": "Immersive ceramic courses in Salemi, combining hands-on learning with everyday life in western Sicily.",
    "category": "Brand overview",
    "region": "Leatherback network",
    "website": "https://www.salemiceramics.com/",
    "instagram": "https://www.instagram.com/salemi.ceramics/",
    "facebook": "https://www.facebook.com/profile.php?id=61551791400320",
    "brandFilesUrl": "https://drive.google.com/drive/u/1/folders/1Ztb_qZ8-sqYRKOIrVk_Z_TH0qfdfH09f",
    "brandFilesLabel": "Brand files",
    "brandGuidelinesUrl": "https://drive.google.com/drive/u/1/folders/1KCxOY9HhUC-GoJMfISAj347dMdPRa_V4",
    "brandColours": "Main Colours: 2436BE (Dark blue)",
    "registrationStatus": "Registered",
    "legalEntityOwner": "Salemi School of Ceramics SRL",
    "logoUrl": "https://v5.airtableusercontent.com/v3/u/55/55/1784059200000/iizkoWX9cBhpX5wteBe3Ew/5zi3Qgh9ReykpwTjA6GvypSKFYSltD9za2ibItQBgGTphLFkTIYjORSqX4RU18PI4E1zRhk_vb8RijmUjBYWSfmiEmThckuTqcG_MpvLlReqX6nomFq3If08v3OAjuQIyf4SoabbuZATh_67ZZ9_D1Gtzf3Ko0tCTpaEEc2f6Zk/mez8feooNbFuVnRZiHuGYsnUWDiIuXKflHNqfiqldDQ",
    "logoTone": "dark",
    "status": "active",
    "accent": "#2436BE"
  },
  {
    "id": "rec7ZxyaUQjytYLXS",
    "name": "Salt Caravan",
    "description": "Flavor-first slow travel for small groups, curated with food insiders and rooted in local stories.",
    "category": "Brand overview",
    "region": "Leatherback network",
    "website": "https://www.saltcaravan.com/",
    "instagram": "https://www.instagram.com/saltcaravan.travel/",
    "brandFilesUrl": "https://drive.google.com/drive/folders/1-0PMQ3LqlH_HW2dmgDa9rOtOHgftgdGz",
    "brandFilesLabel": "Brand files",
    "brandGuidelinesUrl": "https://drive.google.com/drive/folders/148jcoNkJDLdL0sa4wONQXLwdSDhdaYse?usp=drive_link",
    "productBriefUrl": "https://docs.google.com/document/d/1luZoTcq2Pwwzq0FvG5z1jfJT3Drgv5ikkjSzxjvlkAM/edit?usp=drive_link",
    "brandColours": "#5d224d (Eggplant)\n#60cb99 (Mint)\n#f7f4e1 (Cream, accent colour)",
    "registrationStatus": "Status not set",
    "legalEntityOwner": "Leatherback Travel Pty Ltd",
    "logoUrl": "https://v5.airtableusercontent.com/v3/u/55/55/1784059200000/FhLUdrk2Cy7zQ2L-7NE0PA/6hErL5e1HceWdd0RELPFpeJqh7OYECXwTJn8W9RTRkwiTC25Ze9zyMnnctHUzbKjLQ3fWVfW5nGK61J8CqByNIbJ4Jmzb6w5Szyfc52TAGpy_1P6OH4tgjYRVudgm9kfJtNuPemDzl89SwzHeVjLZOpvhlhni55C1KQmyWQbbADBImVKbQnzqrl8PCxBj7hR5BPhsTqdZzd-mMspxOTL2SBJ2Or2cZk2euGH5eqkud4/AILqBdlPwc5vHsUbb2UHjPw1PUvvDSkbBFjxvw6p1YI",
    "logoTone": "dark",
    "status": "developing",
    "accent": "#5d224d"
  }
];
