"use server";

// Server actions behind the week calendar's click-to-book composer. Any
// signed-in booking user (BM or Pod Lead) may book a guest onto any BM's
// calendar — provenance is kept honest by source_kind 'internal' plus
// booked_by, never by pretending the guest booked it themselves.

import { revalidatePath } from "next/cache";
import { DateTime } from "luxon";
import { requireBookingAccess } from "@/lib/booking/access";
import { appUrl } from "@/lib/booking/app-url";
import { resolveSchedulingZone } from "@/lib/booking/availability/engine";
import { getBrandById, getEventTypesForBrand, getStaffBySlug } from "@/lib/booking/availability/service";
import { searchCustomers, type CustomerHit } from "@/lib/booking/customers";
import { databaseConfigured } from "@/lib/booking/db";
import { createBooking } from "@/lib/booking/service";

export type GuestSearchResult = { ok: true; hits: CustomerHit[] } | { ok: false; error: string };

export async function searchGuestsAction(query: string): Promise<GuestSearchResult> {
  await requireBookingAccess("booking.read");
  try {
    return { ok: true, hits: await searchCustomers(String(query ?? "")) };
  } catch (error) {
    return { ok: false, error: error instanceof Error ? error.message : "Guest search failed." };
  }
}

export type InternalBookingInput = {
  staffSlug: string;
  /** Local calendar day (yyyy-LL-dd) and minutes from midnight, both in the BM's scheduling zone. */
  dayKey: string;
  startMin: number;
  eventTypeKey: string;
  guestName: string;
  guestEmail: string;
  guestPhone: string;
  callMedium: "video" | "phone";
  notes: string;
  /** Generated by the composer when it opens, so a double-click cannot double-book (public /book convention). */
  idempotencyKey: string;
};

export type InternalBookingResult =
  | { ok: true; timeLabel: string }
  | { ok: false; error: string };

const FAIL_COPY: Record<string, string> = {
  slot_taken: "That time is busy or already booked — pick another.",
  slot_invalid:
    "That time is not bookable: outside working hours, in the past, or within the BM's minimum notice.",
  calendar_failed: "Google Calendar could not be reached — the booking was not made.",
};

export async function bookInternalAction(input: InternalBookingInput): Promise<InternalBookingResult> {
  const access = await requireBookingAccess("booking.read");
  if (!databaseConfigured()) return { ok: false, error: "The booking database is not configured." };

  if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(String(input.idempotencyKey ?? ""))) {
    return { ok: false, error: "Missing booking token — reload and try again." };
  }

  const staff = await getStaffBySlug(String(input.staffSlug));
  if (!staff || !staff.active) return { ok: false, error: "Unknown Booking Manager." };
  const brand = staff.primaryBrandId ? await getBrandById(staff.primaryBrandId) : null;
  if (!brand) return { ok: false, error: `${staff.fullName} has no primary brand set.` };

  const eventTypes = await getEventTypesForBrand(brand.id);
  const eventType = eventTypes.find((candidate) => candidate.key === input.eventTypeKey && candidate.active);
  if (!eventType) return { ok: false, error: "Unknown call type for this brand." };

  const guestName = String(input.guestName ?? "").trim();
  const guestEmail = String(input.guestEmail ?? "").trim();
  if (!guestName) return { ok: false, error: "The guest needs a name." };
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(guestEmail)) {
    return { ok: false, error: "The guest needs a valid email — confirmations and reminders go there." };
  }
  const guestPhone = String(input.guestPhone ?? "").trim() || null;
  const callMedium = input.callMedium === "phone" ? "phone" : "video";
  if (callMedium === "phone" && !guestPhone) {
    return { ok: false, error: "A phone call needs the guest's phone number." };
  }
  if (callMedium === "video" && !staff.videoCallsEnabled) {
    return { ok: false, error: `${staff.firstName} is phone-only — book this as a phone call.` };
  }

  const zone = resolveSchedulingZone(staff, brand);
  const startMin = Math.trunc(Number(input.startMin));
  const day = DateTime.fromFormat(String(input.dayKey), "yyyy-LL-dd", { zone });
  if (!day.isValid || !Number.isFinite(startMin) || startMin < 0 || startMin >= 24 * 60) {
    return { ok: false, error: "That time could not be understood." };
  }
  const start = day.startOf("day").plus({ minutes: startMin });

  const result = await createBooking({
    staff,
    brand,
    eventType,
    startIso: start.toUTC().toISO()!,
    guestName,
    guestEmail,
    guestPhone,
    callMedium,
    sourceKind: "internal",
    sourceSlug: staff.slug,
    bookedBy: access.identity.email,
    internalNotes: String(input.notes ?? "").trim() || null,
    idempotencyKey: input.idempotencyKey,
    appUrl: appUrl(),
  });

  if (!result.ok) return { ok: false, error: FAIL_COPY[result.reason] ?? "The booking failed." };

  revalidatePath("/booking");
  revalidatePath(`/booking/team/${staff.slug}`);
  return {
    ok: true,
    timeLabel: `${start.toFormat("ccc d LLL, h:mm a")}–${start
      .plus({ minutes: eventType.durationMin })
      .toFormat("h:mm a")} (${zone})`,
  };
}
